DELETE http://localhost:3003/api/blogs/6738fbcd14fb28596c912d6f
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhbyIsImlkIjoiNjczOGY3YmY0YzlhNzcyMThkOWI1MWNhIiwiaWF0IjoxNzMxODEwMTU4fQ.HKCoG_f2jonvQbAm2Y4VVOgprg2IDmtnLqCCvMc2eIA